apiVersion: xl-release/v1
kind: Templates
spec:
  - template: Dep 1
    phases:
      - phase: Phase 1
        tasks:
          - name: Task 1
            type: xlrelease.GateTask

            Test


    ests

    asdfasf
ataestsdfasdf
